--- Wysy³anie AB

---drop procedure POLARYS.DKKRAP069;
CREATE OR REPLACE PROCEDURE POLARYS.DKKRAP069(
	PARFIRMA DECIMAL(2, 0), 
	PARDATWPROD DECIMAL(8, 0),
	PARDATWPRDO DECIMAL(8, 0)
)
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL
	SPECIFIC POLARYS.DKKRAP069 
	DETERMINISTIC
  	READS SQL DATA
BEGIN
---	DECLARE idProgram  INTEGER;
	
DECLARE C1 CURSOR FOR

select  NYY, NKOMNR, 

NKDAUF, 
NLIEFW, 
NKOMNA, 
R.RPOSNR,  
R.RARTNR, 
R.RABEZ, 
R.RMENGE, 
R.RBEPRS, 
NUDAT,

NKDNR, 
NNAME, 
(SELECT NAZWA FROM NEWAGE.KLIENT WHERE FIRMA=NFIRM AND KLIENTNR=NKDNR) AS OPIS_KLIENTA, 


NLOEKZ 
from kldat2.tauk#t N LEFT JOIN KLDAT2.TAUP#T R ON 
            N.NFIRM = R.RFIRM AND 
			N.NWW = R.RWW AND 
			N.NYY = R.RYY AND 
			N.NKOMNR = R.RKOMNR 
where nfirm=PARFIRMA and nww=20 and NUDAT BETWEEN PARDATWPROD AND  PARDATWPRDO
           AND NKDNR IN (SELECT SKLEP FROM NEWAGE.GRUPYK WHERE FIRMA=1  AND KLIENT IN (1102, 1101) )  AND NLOEKZ=''
		   
FOR READ ONLY ; 

---SET idProgram   = SQLF.SO_GET_KAT_ID( '#PROG#DKKKMK');


OPEN C1 ;
SET RESULT SETS CURSOR C1 ;

END  ;
COMMENT ON SPECIFIC procedure POLARYS.DKKRAP069 IS 	'LISTA WPROWADZONYCH ZAMOWIEN DLA LEINER KIKA' ; 
GRANT EXECUTE ON procedure POLARYS.DKKRAP069 TO PUBLIC  ; 
CALL POLARYS.DKKRAP069(1, 20190130, 20190131)