drop procedure NEWAGE.PINS2CECH4Z;  
--  Generuj SQL 
--  Wersja:                    	V6R1M0 080215 
--  Wygenerowano:              	12.04.26 23:42:57 
--  Relacyjna baza danych:     	ASNOWE 
--  Opcja standardów:          	DB2 for i 

SET PATH *LIBL ; 
  
CREATE PROCEDURE NEWAGE.PINS2CECH4Z ( 	
	IN P_FIRM DECIMAL(2, 0),
	IN P_DATOBOW  DECIMAL(8, 0) 
) 	
	LANGUAGE SQL 	
	SPECIFIC NEWAGE.PINS2CECH4Z  	
	DETERMINISTIC 	
	MODIFIES SQL DATA 	
	
	
	BEGIN 
	declare   $zamh_idy integer;
	
INSERT  INTO ZLECDAT.CECH4Z#T  ( FIRMA, NRKLIENTA, INDEKS,  USERZ) 
SELECT DISTINCT FIRM, KDNR, TEILN, 'AUTOMX' AS USERZ    FROM ZLECDAT.CECH4H#T  WHERE FIRM=P_FIRM AND DTAOB<=P_DATOBOW AND DTADO>=P_DATOBOW
  AND NOT  EXISTS ( SELECT 1  FROM ZLECDAT.CECH4Z#T WHERE FIRM=FIRMA AND INDEKS=TEILN AND KDNR=NRKLIENTA); 
							 
END  
;

---	INSERT INTO NEWAGE.ZDARZENIE ( FIRMA, IDENT, TABELA, TYP, LP, RODZAJ, STATUS, OPIS, UWAGI, OPERATOR ) 
--		VALUES ( 80, 1 , 'ZLECDAT.ZAMP#T', 'T', 0, 'EKSP_WE', '00340277441222867304', 'Data przyj:' || 20190101, 'nic', 'SYSTEM'   )

COMMENT ON SPECIFIC procedure NEWAGE.PINS2CECH4Z IS 	'DKK, KOPIOWANIE Z NAGLOWKA CENNIKA DO ZATWIERDZONYCH' ; 

GRANT EXECUTE ON procedure NEWAGE.PINS2CECH4Z TO PUBLIC  ;

CALL NEWAGE.PINS2CECH4Z(1, 20200128 );